# models/sources.yml

version: 2

sources:
  - name: redshift_system
    tables:
      - name: svv_table_info
  - name: mock_system
    schema: mock_redshift
    tables:
      - name: mock_svv_table_info
