name: "dbt_redshift_stats"
version: "1.0.0"
config-version: 2

profile: "dbt_redshift_stats"

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  redshift_stats:
    monitoring:
      materialized: table
      schema: monitoring

# Vars
vars:
  monitored_schemas:
    external:
      - ext_logistics
      - ext_marketing
      - ext_notifications
      - ext_orders
      - ext_products
      - ext_stores
      - ext_users
    production:
      - logistics
      - marketing
      - notifications
      - orders
      - products
      - stores
      - users
    sources:
      - src_logistics
      - src_marketing
      - src_notifications
      - src_orders
      - src_products
      - src_stores
      - src_users
    staging:
      - stg_logistics
      - stg_marketing
      - stg_notifications
      - stg_orders
      - stg_products
      - stg_stores
      - stg_users
  mock_id: ""
